# Site settings
title: Classy Strip
email: 

keywords: webcomic, comic, software, engineer, developer, humor
description: > # this means to ignore newlines until "baseurl:"
  A webcomic.


baseurl: https://classystrip.com
url: / #Leave this, change the baseurl.

# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, image_optim_cache.yml]

# Build settings
markdown: kramdown
kramdown:
  input: GFM

destination: _site

# Compress our Css
#sass:
#    style: :compressed

permalink: /:categories/:title/

#################################################
####CUSTOM

# Set default header image
header: yes
header_sm: images/banner/banner-small/banner.png
header_med: images/banner/banner-med/banner.png
header_large: images/banner/banner-large/banner.png
header_xl: images/banner/banner-xl/banner.png

## Thumbnailer taken from https://github.com/chrisanthropic/jekyll-minimagick

# Autogenerate thumbs for comics
mini_magick:

#Create Thumbs for the Archive Page
    thumbnail:
      source: images/comics/
      destination: /images/comics/thumbs
      resize: "182x280^"

#Autogenerate smaller size for small screens
    small:
      source: images/comics/
      destination: /images/comics/small
      resize: "350x535^"

    banner-small:
      source: images/banner/banner-xl2
      destination: /images/banner/banner-small/
      resize: "640x100^"

    banner-med:
      source: images/banner/banner-xl2
      destination: /images/banner/banner-med/
      resize: "1024x160^"

    banner-large:
      source: images/banner/banner-xl2
      destination: /images/banner/banner-large/
      resize: "1440x225^"

    banner-xl:
      source: images/banner/banner-xl2
      destination: /images/banner/banner-xl/
      resize: "1920x300^"

#### SEO Stuff
# Google Analytics
google_universal_analytics: UA-107716052-1
google_universal_analytics_cookiedomain: auto

# Facebook Opengraph
facebook_user:
facebook_app_id:                      #enter your App ID
facebook_locale: en_US
facebook_page:                        #the URL of your Facebook Page
facebook_image: /images/classystriplogo.png #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Twitter Cards
twitter_author: pcatre
twitter_user: classycostrip
twitter_card: true
twitter_image: /images/classystriplogo.png  #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: classystrip